dynatrace:
  target: dev
  outputs:
    dev:
      type: postgres
      host: <hostname-here>
      user: postgres
      password: <password-here>
      port: 5432
      dbname: postgres # or database instead of dbname
      schema: dbt_dynatrace
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections

      
